-- CreateTable
CREATE TABLE `DossierInscription` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `anneeScolaire` VARCHAR(191) NOT NULL DEFAULT '2025/2026',
    `dateDepot` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `pereNom` VARCHAR(191) NOT NULL,
    `perePrenom` VARCHAR(191) NOT NULL,
    `pereProfession` VARCHAR(191) NULL,
    `pereTelephone` VARCHAR(191) NOT NULL,
    `pereEmail` VARCHAR(191) NOT NULL,
    `mereNom` VARCHAR(191) NOT NULL,
    `merePrenom` VARCHAR(191) NOT NULL,
    `mereProfession` VARCHAR(191) NULL,
    `mereTelephone` VARCHAR(191) NOT NULL,
    `mereEmail` VARCHAR(191) NOT NULL,
    `adresseComplete` TEXT NOT NULL,
    `telephoneDomicile` VARCHAR(191) NULL,
    `enfantNom` VARCHAR(191) NOT NULL,
    `enfantPrenom` VARCHAR(191) NOT NULL,
    `enfantDateNaissance` DATETIME(3) NOT NULL,
    `enfantSexe` VARCHAR(191) NOT NULL,
    `enfantClasseDemandee` VARCHAR(191) NOT NULL,
    `enfantEcoleActuelle` VARCHAR(191) NULL,
    `enfantDerniereScolarite` VARCHAR(191) NULL,
    `medecinTraitantNom` VARCHAR(191) NULL,
    `medecinTraitantTelephone` VARCHAR(191) NULL,
    `allergies` TEXT NULL,
    `traitementsMedicaux` TEXT NULL,
    `regimeAlimentaire` TEXT NULL,
    `paiNecessaire` BOOLEAN NOT NULL DEFAULT false,
    `besoinsPArticuliers` TEXT NULL,
    `urgence1Nom` VARCHAR(191) NULL,
    `urgence1Prenom` VARCHAR(191) NULL,
    `urgence1Lien` VARCHAR(191) NULL,
    `urgence1Telephone` VARCHAR(191) NULL,
    `urgence2Nom` VARCHAR(191) NULL,
    `urgence2Prenom` VARCHAR(191) NULL,
    `urgence2Lien` VARCHAR(191) NULL,
    `urgence2Telephone` VARCHAR(191) NULL,
    `autorisationPhoto` BOOLEAN NOT NULL DEFAULT false,
    `autorisationVideo` BOOLEAN NOT NULL DEFAULT false,
    `autorisationSortie` BOOLEAN NOT NULL DEFAULT false,
    `autorisationInternet` BOOLEAN NOT NULL DEFAULT false,
    `transportSouhaite` BOOLEAN NOT NULL DEFAULT false,
    `restaurationSouhaitee` BOOLEAN NOT NULL DEFAULT false,
    `joursRestauration` VARCHAR(191) NULL,
    `recuperation1Nom` VARCHAR(191) NULL,
    `recuperation1Prenom` VARCHAR(191) NULL,
    `recuperation1Telephone` VARCHAR(191) NULL,
    `recuperation1Lien` VARCHAR(191) NULL,
    `recuperation2Nom` VARCHAR(191) NULL,
    `recuperation2Prenom` VARCHAR(191) NULL,
    `recuperation2Telephone` VARCHAR(191) NULL,
    `recuperation2Lien` VARCHAR(191) NULL,
    `docCertificatRadiation` BOOLEAN NOT NULL DEFAULT false,
    `docLivretFamille` BOOLEAN NOT NULL DEFAULT false,
    `docJustificatifDomicile` BOOLEAN NOT NULL DEFAULT false,
    `docAssuranceScolaire` BOOLEAN NOT NULL DEFAULT false,
    `docCarnetSante` BOOLEAN NOT NULL DEFAULT false,
    `docCertificatMedical` BOOLEAN NOT NULL DEFAULT false,
    `engagementReglement` BOOLEAN NOT NULL DEFAULT false,
    `engagementFinancier` BOOLEAN NOT NULL DEFAULT false,
    `dateSignature` DATETIME(3) NULL,
    `statut` ENUM('EN_ATTENTE', 'EN_COURS', 'VALIDE', 'REFUSE', 'FINALISE') NOT NULL DEFAULT 'EN_ATTENTE',
    `traitePar` INTEGER NULL,
    `dateTraitement` DATETIME(3) NULL,
    `notesAdministratives` TEXT NULL,
    `documentPdfGenere` VARCHAR(191) NULL,
    `statutImpression` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `DossierInscription_statut_idx`(`statut`),
    INDEX `DossierInscription_anneeScolaire_idx`(`anneeScolaire`),
    INDEX `DossierInscription_dateDepot_idx`(`dateDepot`),
    INDEX `DossierInscription_enfantClasseDemandee_idx`(`enfantClasseDemandee`),
    INDEX `DossierInscription_pereEmail_idx`(`pereEmail`),
    INDEX `DossierInscription_mereEmail_idx`(`mereEmail`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `DossierInscription` ADD CONSTRAINT `DossierInscription_traitePar_fkey` FOREIGN KEY (`traitePar`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
