-- AlterTable
ALTER TABLE `document` MODIFY `type` ENUM('PROJET_EDUCATIF', 'PROJET_ETABLISSEMENT', 'REGLEMENT_INTERIEUR', 'DOSSIER_INSCRIPTION', 'ORGANIGRAMME', 'CHARTE_LAICITE', 'CHARTE_NUMERIQUE', 'CHARTE_VIE_SCOLAIRE', 'CHARTE_RESTAURATION', 'AGENDA', 'PASTORALE_AXE', 'PASTORALE_TEMPS_PRIANT', 'PASTORALE_ENSEMBLE') NOT NULL;
